Fix missing dependency of fs feature (#164)
Currently `cargo build --features fs` fails with:
```rust
error[E0706]: functions in traits cannot be declared `async`
  --> src/fs/extension.rs:21:5
   |
21 |     async fn reset_to_beginning(&mut self) -> Result<(), IoError>;
   |     -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     `async` because of this
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait
```

Co-authored-by: Nick Cardin <nick@cardin.email>